# Generated by Django 2.1.5 on 2019-01-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ivan Pupkin', max_length=1000)),
                ('course', models.CharField(default='Python for Data Science', max_length=1000)),
                ('date', models.DateField(default='2019-01-01')),
                ('mark', models.CharField(default='Excellent', max_length=1000)),
                ('permanent_link', models.CharField(default='AUTO', max_length=1000)),
            ],
        ),
    ]
