# Generated by Django 2.2 on 2019-04-09 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=1000)),
                ('first_name', models.CharField(max_length=1000)),
                ('birth_date', models.DateField(default='2019-01-01')),
                ('iin', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('running', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('score', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cert.Person')),
                ('test_set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cert.TestSet')),
            ],
        ),
    ]
