# Generated by Django 2.2 on 2019-04-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0002_person_test_testset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='DS', max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', max_length=10000)),
                ('answer1', models.CharField(default='', max_length=1000)),
                ('answer2', models.CharField(default='', max_length=1000)),
                ('answer3', models.CharField(default='', max_length=1000)),
                ('answer4', models.CharField(default='', max_length=1000)),
                ('correct_1_to_4', models.IntegerField(default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.Subject')),
            ],
        ),
    ]
