# Generated by Django 2.2 on 2019-04-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0003_question_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Assignment',
        ),
    ]
