# Generated by Django 2.2 on 2019-04-10 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cert', '0004_auto_20190410_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='test_set',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assgn_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assgn_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cert.Certificate'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='finished_date_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='started_date_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TestSet',
        ),
    ]
