# Generated by Django 2.2 on 2019-04-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0005_auto_20190410_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('quantity1', models.IntegerField(default=10)),
                ('quantity2', models.IntegerField(default=0)),
                ('quantity3', models.IntegerField(default=0)),
                ('quantity4', models.IntegerField(default=0)),
                ('quantity5', models.IntegerField(default=0)),
                ('quantity6', models.IntegerField(default=0)),
                ('quantity7', models.IntegerField(default=0)),
                ('quantity8', models.IntegerField(default=0)),
                ('quantity9', models.IntegerField(default=0)),
                ('quantity10', models.IntegerField(default=0)),
                ('quantity11', models.IntegerField(default=0)),
                ('quantity12', models.IntegerField(default=0)),
                ('subject1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub1', to='cert.Subject')),
                ('subject10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub10', to='cert.Subject')),
                ('subject11', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub11', to='cert.Subject')),
                ('subject12', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub12', to='cert.Subject')),
                ('subject2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub2', to='cert.Subject')),
                ('subject3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub3', to='cert.Subject')),
                ('subject4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub4', to='cert.Subject')),
                ('subject5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub5', to='cert.Subject')),
                ('subject6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub6', to='cert.Subject')),
                ('subject7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub7', to='cert.Subject')),
                ('subject8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub8', to='cert.Subject')),
                ('subject9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub9', to='cert.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(default=0)),
                ('correct', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cert.Person')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cert.Question')),
            ],
        ),
    ]
