# Generated by Django 2.2 on 2019-04-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0007_assignment_quiz_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(default='idle', max_length=10),
        ),
    ]
