# Generated by Django 2.2 on 2019-04-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0009_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cert.Question'),
        ),
    ]
