# Generated by Django 2.2 on 2019-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0010_assignment_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstructure',
            name='minutes',
            field=models.IntegerField(default=120),
        ),
    ]
