# Generated by Django 2.2 on 2019-04-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0011_quizstructure_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedquestion',
            name='person',
        ),
        migrations.AddField(
            model_name='assignedquestion',
            name='assignment',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='cert.Assignment'),
        ),
    ]
