# Generated by Django 2.2 on 2019-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0013_assignedquestion_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='finished_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='started_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
