# Generated by Django 2.2 on 2019-04-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0014_auto_20190412_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_code',
        ),
    ]
