# Generated by Django 2.2 on 2019-04-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0015_remove_assignment_assigned_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizstructure',
            name='minutes',
            field=models.IntegerField(default=60),
        ),
    ]
