# Generated by Django 2.2 on 2019-04-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0016_auto_20190413_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('text', models.TextField(default='', max_length=10000)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
