# Generated by Django 2.2 on 2019-04-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0017_auto_20190416_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
