# Generated by Django 2.2 on 2019-04-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0019_sendemail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
