# Generated by Django 2.2 on 2019-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0020_assignment_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='coefs',
            field=models.CharField(default='1 1', max_length=1000),
        ),
        migrations.AddField(
            model_name='assignment',
            name='finished_regression',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='finished_regression_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='regression_task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='started_regression',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='started_regression_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
