# Generated by Django 2.2 on 2019-04-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0021_auto_20190420_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='regression_solution',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
