# Generated by Django 2.2 on 2019-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0022_assignment_regression_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='regression_tries_left',
            field=models.IntegerField(default=5),
        ),
    ]
