# Generated by Django 2.2 on 2019-05-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0025_assignment_regression_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
