# Generated by Django 2.2 on 2019-06-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0027_auto_20190510_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstructure',
            name='regression',
            field=models.BooleanField(default=False),
        ),
    ]
