# Generated by Django 2.2 on 2019-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0028_quizstructure_regression'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstructure',
            name='issue_certificate',
            field=models.BooleanField(default=True),
        ),
    ]
