# Generated by Django 2.2 on 2020-03-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0029_quizstructure_issue_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='localhost', max_length=50)),
                ('text', models.TextField(default='\n        Здравствуйте, {{assignment.person.first_name}}!\n        {{assignment.quiz_structure.name}}\n        {{assignment.quiz_structure.minutes}}\n        \n        {{assignment.quiz_structure.quantity()}}\n        Логин: {{assignment.person.user.username}}\n        Пароль: {{assignment.person.password}}\n    ', max_length=10000)),
                ('port', models.IntegerField(default=465)),
                ('sender_email', models.CharField(default='dsacademy.kz@gmail.com', max_length=50)),
                ('subject', models.CharField(default='Тестовая система Data Science Academy', max_length=50)),
                ('smtp_server', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('login', models.CharField(default='dsacademykz@gmail.com', max_length=50)),
                ('password', models.CharField(default='dsadsa5918', max_length=50)),
            ],
        ),
    ]
