# Generated by Django 2.2 on 2020-03-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0030_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.TextField(default='\nЗдравствуйте, {{assignment.person.first_name}}!\n{{assignment.quiz_structure.name}}\n{{assignment.quiz_structure.minutes}}\n\n{{assignment.quiz_structure.quantity()}}\nЛогин: {{assignment.person.user.username}}\nПароль: {{assignment.person.password}}\n    ', max_length=10000),
        ),
    ]
