# Generated by Django 2.2 on 2020-03-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0031_auto_20200331_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='html',
            field=models.TextField(default='\n    <html>\n    <body><p>\n    Здравствуйте, {{assignment.person.first_name}}!\n    {{assignment.quiz_structure.name}}\n    {{assignment.quiz_structure.minutes}}\n\n    {{assignment.quiz_structure.quantity()}}\n    Логин: {{assignment.person.user.username}}\n    Пароль: {{assignment.person.password}}\n    </p>\n    </body>\n    </hmtl>\n        ', max_length=10000),
        ),
    ]
