# Generated by Django 2.2 on 2020-03-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0033_auto_20200331_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='html',
            field=models.TextField(default='\n<html>\n<body><p>\nЗдравствуйте, {{assignment.person.first_name}}!<br>\n{{assignment.quiz_structure.name}}<br>\n{{assignment.quiz_structure.minutes}}<br>\n<br>\n{{assignment.quiz_structure.quantity()}}<br>\nЛогин: {{assignment.person.user.username}}<br>\nПароль: {{assignment.person.password}}<br>\n</p>\n</body>\n</hmtl>\n        ', max_length=10000),
        ),
    ]
